apiVersion: v1
kind: Service
metadata:
  name: nginx-service-nodeport
spec:
  ports:
    - port: 8000
      targetPort: 80
      nodePort: 8080
      protocol: TCP
  type: NodePort
  selector:
    name: nginx
