apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod-volumes
spec:
  containers:
    - name: test-container
      image: ubuntu
      command: [ "/bin/sh","-c","cat /etc/config/path/to/special-key" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: special-config
        items:
        - key: special.how
          path: path/to/special-key
  restartPolicy: Never
